### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by Schaeff** [matter-labs/bellman#18]
Currently we have to point to commit `9e35737` to benefit from the [singlecore fix](https://github.com/matter-labs/bellman/issues/13).

It seems like the commits after that have breaking changes due to futures, so I was wondering if you could release `9e35737` to crates.io so that the latest version before these changes is out there?

Thanks!

**Comment by shamatar** [comment]
Hey Schaeff! What exactly is a reason to panic? Single core fix is present is the latest futures. I assume it’s something in the next thread pool executor?
