### ISSUE TITLE
Testing multicore

### ISSUE THREAD

**Issue by muazzamalikazmi** [matter-labs/bellman#25]
The following is supposed to be the benchmark for large data:
`cargo test --release -- --ignored --nocapture test_multiexp_performance_on_large_data`

Apparently, it's broken.  I tried it on my local PC as well as Google Cloud instance.  In both cases, no test or benchmark is run. 

Am I missing something?

![image](https://user-images.githubusercontent.com/8564798/87076196-d4a9a200-c23a-11ea-8911-1752b579cc74.png)

**Comment by shamatar** [comment]
Hello @muazzamalikazmi 

This should only work if you are in a right branch where test exists.
