### ISSUE TITLE
Enforce for Transpiler in PLONK system

### ISSUE THREAD

**Issue by skipjack8** [matter-labs/bellman#32]
In the `enforce` function for `Transpiler`, when handle the type of constraint `LC * const = LC` or `const * LC = LC`,  the `free_constant_term` is set as follows. 
https://github.com/matter-labs/bellman/blob/f551a55d83d2ea604b2dbfe096fd9dcfdaedb189/src/plonk/better_cs/adaptor.rs#L1030-L1032
However,  the `free_constant_term` should be initialized as `a_constant_term` or `b_constant_term`, depending on which one is the linear combination.

**Comment by shamatar** [comment]
Hello @skipjack8 

Thank you for a good catch. Looks like in my internal tests and in our circuits in general we never had a case with B and C terms being constant, so it was missed. I'll fix it immediately. 

Sincerely, Alex

**Comment by shamatar** [comment]
Fix is merged into `beta` and `dev` branches. The easiest way to use it is to use franklin-crypto `beta` or `dev` branch respectively. 

Feel free to reopen or continue the discussion here

**Comment by skipjack8** [comment]
Hello, similar cases happened in other types of circuit in `beta` branch.
1.  circuit like LC * const = LC or const * LC = LC
https://github.com/matter-labs/bellman/blob/48441155ec7006bf7bfac553b5fb7d466d7fcd00/src/plonk/better_cs/adaptor.rs#L994-L1001
Since the `free_term_constant` should include the constant term of c, the 4th parameter  should probably be `c_constant_term`, instead of `zero_fr`.
2.  const * const = LC
https://github.com/matter-labs/bellman/blob/48441155ec7006bf7bfac553b5fb7d466d7fcd00/src/plonk/better_cs/adaptor.rs#L1067-L1083
`c_constant_term` has also been ignored here, and  the 4th parameter `free_constant_term `  of `enforce_lc_as_gates`  should be `c_constant_term - a_constant_term  * b_constant_term`.

**Comment by shamatar** [comment]
Hey @skipjack8 

For the first case you have linked the code that does special treatment for something like 0 * LC = 0, (that is a junk constraint, I think) while the case you describe happens below

For the second case I'll check again
