### ISSUE TITLE
Question about plonk proof input fields

### ISSUE THREAD

**Issue by DreamWuGit** [matter-labs/bellman#42]
hi, experts
I see bellman plonk proof structure
pub struct Proof<E: Engine, P: PlonkConstraintSystemParams<E>> {
    **pub num_inputs: usize,**
    pub n: usize,
    **pub input_values: Vec<E::Fr>,**
    pub wire_commitments: Vec<E::G1Affine>,
    pub grand_product_commitment: E::G1Affine,
    pub quotient_poly_commitments: Vec<E::G1Affine>,
  pub wire_values_at_z: Vec<E::Fr>,
    pub wire_values_at_z_omega: Vec<E::Fr>,
    pub grand_product_at_z_omega: E::Fr,
    pub quotient_polynomial_at_z: E::Fr,
    pub linearization_polynomial_at_z: E::Fr,
    pub permutation_polynomials_at_z: Vec<E::Fr>,
    pub opening_at_z_proof: E::G1Affine,
    pub opening_at_z_omega_proof: E::G1Affine,
    pub(crate) _marker: std::marker::PhantomData<P>
}
my understanding of  filed num_inputs is number of public input elements
and  field " input_values" is public input element 's values ,  So the input_values.length should be equal to num_inputs? if yes,  num_inputs can be omit , am I right ? correct me if I am wrong ,
Thanks a lot

**Comment by shamatar** [comment]
Well, they have a little bit different meaning from my perspective:
- num_inputs determines a property of the proven statement (for various proofs acceptable by this circuit)
- input_values are concrete inputs into the given proof

But in practice you can indeed just keep a vector only

**Comment by DreamWuGit** [comment]
@shamatar  thanks your response,  could u talk more about first one ? which property of  the proven statement ? I know there can be multi proofs for certain circuit as various input values provide .

Thanks !

**Comment by shamatar** [comment]
The "num_inputs" is a property of the statement, but I agree that in the proof your are ok to have only a vector of input values and a separate "num_inputs" is redundant because the same information (num_inputs) is also located in the verification key, so at any point in time you will have both for actual verification.

I hope it clarifies my previous answer a little

**Comment by DreamWuGit** [comment]
understood & thanks ！
